# Evaluation prompts
knowledge_explanation: |
    你是一个有多年小学数学教学经验的标注员。我给你一段【输入文本】，这是数学教师给学生讲解知识点的文本。你依据【学生画像】【学生需求】，根据【标注规则】，从讲解语言、讲解策略、个性化三个维度，对文本进行评分。

    ##评分标准##
    每个-{评分点}-的满分是5分，你给出1-5的评分。

    ##评分标准##
    **讲解语言**：
    -角色贴合性-：符合教师身份，有一定专业性和权威性；不要尝试与用户进行动作互动；也不要尝试对教学方法或者教学原理进行介绍说明。 
    -语言流畅性-：语言清晰流畅；讲解文本充分，而不是简单逻辑框架；
    -语气温和-：语言温柔平和，语气不跳脱。
    **讲解策略**：
    -教学方法合理性-：使用的科学的教学方法，如支架式教学、引导式教学等；教学的步骤和逻辑合乎常理
    -内容设计合理性-：教学的引入、举例都符合学生的年级，不涉及超过学生认知阶段的知识或者物体、社会事件
    **个性化**：
    -用户特征呼应-：对学生的个人画像有所呼应，比如关注到他的年级、年龄或者他主动提出的兴趣爱好等其他个人信息。

    ##学生画像##
    {Student_image} 

    ##学生需求##
    {Student_query} 

    ##输入文本##
    {LLM_response}

    ##输出##
    你严格按照下文json格式输出，不要输出其他内容。
    {
        "角色贴合性":分数,
        "语言流畅性":分数,
        "语气温和":分数,
        "教学方法合理性":分数,
        "内容设计合理性":分数,
        "用户特征呼应":分数
    }



contextual_problem: |

    请你作为一名教育专家，基于以下评估指标，对给定的一道题目进行详细评估，并对每个子维度按李克特五点量表打分（1-5分，1分为“完全不符合”，5分为“完全符合”），并简要说明评分理由：
            一、题目内容质量
            1. 题目表述是否清晰易懂，避免了含糊或容易引起误解的表述
            2. 题目是否可解、存在正确解，对于单选题是否导向唯一答案
            3. 题目是否切实考察了所指定的知识点，符合课标要求
            4. 是否切实体现了教师所提及的核心素养要求
            5. 难度是否与教师指定难度大致一致
            二、答案与解析质量
            1. 答案是否准确，涵盖所有可能的正确答案
            2. 解析是否涵盖主流解题思路，紧扣当前知识点，无超纲内容
            3. 解析是否逻辑清晰、无明显跳跃，步骤合理
            三、题目情境质量
            1. 情境是否来源于现实生活，符合学生认知水平
            2. 情境是否与考察知识点融合成有机整体，而非割裂并置
            3. 情境表述是否规范、结构是否简洁清晰
            4. 情境故事是否符合社会主义核心价值观，不能违背“立德树人”精神

            请根据以下内容进行评估，主要评估生成题目的质量，模型回复的前后引导语不参与评估：
            教师要求：{prompt}
            模型回复：{query}
            请将最终结果严格以以下JSON格式输出，不得更改键名，score为该维度的得分，comment为你打分的理由，1-5分，1分为“完全不符合”，5分为“完全符合”，结构如下所示：
            {{
                "题目内容质量": {{
                    "题目表述清晰易懂": {{"score": 1, "comment": "在这里写你打分的理由"}},
                    "题目可解且有明确答案": {{"score": 5, "comment": "在这里写你打分的理由"}},
                    "考察知识点符合课标": {{"score": 4, "comment": "在这里写你打分的理由"}},
                    "体现核心素养": {{"score": 3, "comment": "在这里写你打分的理由"}},
                    "难度与教师要求一致": {{"score": 5, "comment": "在这里写你打分的理由"}},
                }},
                "答案解析质量": {{
                    "答案准确完整": {{"score": 5, "comment": "在这里写你打分的理由"}},
                    "解析思路主流、相关性强": {{"score": 4, "comment": "在这里写你打分的理由"}},
                    "解析逻辑清晰": {{"score": 5, "comment": "在这里写你打分的理由"}},
                }},
                "题目情境质量": {{
                    "情境贴近现实、符合认知": {{"score": 2, "comment": "在这里写你打分的理由"}},
                    "情境与知识融合": {{"score": 3, "comment": "在这里写你打分的理由"}},
                    "表述清晰结构简单": {{"score": 1, "comment": "在这里写你打分的理由"}},
                    "符合社会主义核心价值观": {{"score": 2, "comment": "在这里写你打分的理由"}}
                }}  
            }}