
# 知识点讲解场景的任务
knowledge_explanation:
  # 学生画像{image},学生需求{query}
  # 任务1：有理数预习
  task1:
    image: |
      小学二年级，女生，很喜欢数学

    query: |
      下节课学习有理数，你帮我预习

  # 任务2：
  task2:
    image: |
      小学生二年级，男生

    query: |
      你解释为什么要先算乘除再算加减，但有括号的时候要先算括号

  task3:
    image: |
      小学三年级，数学不好

    query: |
      你帮我巩固一下毫米和分米的换算

  task4:
    image: |
      小学三年级，刚考学过除法

    query: |
      你帮我预习一下小数


guided_teaching:
  # 引导式讲题
  |
  测试


interdisciplinary_task:
  # 
  |
  测试



contextual_problem:
    task1: |
      你是一位教研员，正在培训新教师命题。请设计一道具代表性的情景化题目，涵盖四舍五入知识点，主要考察学生数感素养，适用于五年级上，难度为简单。请输出题目、答案和解析。
    task2: |
      你是教育测评系统的内容专家，需设计一道阶段性评估题，题目需要依托于真实生活情境，基于分数比较大小知识点，所考察核心素养为运算能力、数据意识，难度较高，适用于五年级下的学生。请输出题目、答案和解析。
    task3: |
      你正在为学生生成个性化课后作业。根据其年级（七年级上）、知识点（一元一次方程-复习小结）、核心素养（运算能力、推理能力、应用意识）生成一道较高难度的情景化题目。请输出题目、答案和解析。
    task4: |
      你是教辅图书的命题编辑，请撰写一道情景化题目，覆盖五年级上的有序数对确定点的位置知识点，体现空间观念素养，难度为简单。请输出题目、答案和解析。
    task5: |
      你是智能学习系统的诊断模块。请生成一题用于检测学生对约分与最简分式的掌握情况，适用于八年级上，所考察核心素养为运算能力，难度为中等的情境化题目。请输出题目、答案和解析。
    task6: |
      你是基础教育出版社的题目审稿人，请模拟一道符合四年级上阶段认知水平的题目，覆盖公顷和平方千米-复习小结，体现量感、应用意识的核心素养，难度较高。请输出题目、答案和解析。
    task7: |
      你是一位任课教师，正在为五年级上的教学单元准备练习题。请设计一道符合教学目标的题目，帮助学生理解有序数对确定点的位置知识点，同时体现空间观念的核心素养，难度为中等。请输出题目、答案和解析。
